name: Compile Swiftware

on: [push, pull_request]

jobs:
  windows:
    name: Test on Windows
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1.4.1
    - name: compile
      working-directory: ./Swiftware/
      run: | 
        cl src/main.cpp /std:c++latest
